services:
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    entrypoint:
      - /bin/bash
      - -c
      - "/bin/ollama serve & sleep 5; ollama pull qwen2.5vl:3b; wait"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3

  telegram-bot:
    build: .
    depends_on:
      - ollama
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - OLLAMA_BASE_URL=http://ollama:11434
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    volumes:
      - /tmp:/tmp # For temporary image processing
    healthcheck:
      test: ["CMD", "ps", "aux", "|", "grep", "python"]
      interval: 60s
      timeout: 10s
      retries: 3

volumes:
  ollama-data:

networks:
  default:
    name: zkyc-telegram-network
