services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    entrypoint:
      - /bin/bash
      - -c
      - "/bin/ollama serve & sleep 5; ollama pull qwen2.5vl:3b; wait"
    restart: unless-stopped

  telegram-bot:
    build: .
    container_name: zkyc-telegram-bot
    depends_on:
      - ollama
    environment:
      - TOKEN=${TELEGRAM_BOT_TOKEN}
      - OLLAMA_BASE_URL=http://ollama:11434
      - QWEN_MODEL=qwen2.5vl:3b
    volumes:
      - /tmp:/tmp
    restart: unless-stopped
    init: true

volumes:
  ollama_data:
