services:
  ollama:
    image: "docker.io/ollama/ollama"
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    entrypoint:
      [
        "/usr/bin/bash",
        "-c",
        "/bin/ollama serve & sleep 5; ollama pull qwen2.5vl:3b; wait",
      ]
  zk_bot:
    image: ghcr.io/tanguyvans/zkyc-telegram-2:latest
    environment:
      - TOKEN=${TOKEN}
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - ollama
    restart: always

volumes:
  ollama_models:
