services:
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    entrypoint:
      - /bin/bash
      - -c
      - "/bin/ollama serve & sleep 5; ollama pull qwen2.5vl:3b; wait"

  zkyc-qwen:
    image: ghcr.io/tanguyvans/zkyc:qwen-1.0
    ports:
      - "8000:8000"
    depends_on:
      - ollama
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434

volumes:
  ollama-data:
